parameters:
#    nettech_drupal.example.class: Nettech\Bundle\DrupalBundle\Example

services:
#    nettech_drupal.example:
#        class: %nettech_drupal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
